[target.bpfel-unknown-none]
runner = "true"
rustflags = [
    "-Z", "unstable-options",
    "-C", "linker-flavor=bpf", # 🔥 修复：使用 bpf 风格并开启 unstable 选项
    "-C", "linker=bpf-linker",
    "-C", "link-arg=-O",
    "-C", "link-arg=3",
    "-C", "link-arg=--btf",
]

